### ISSUE TITLE
Sidekiq Instrumentation a little spammy with span events

### ISSUE THREAD

**Issue by choubacha** [open-telemetry/opentelemetry-ruby-contrib#405]
The sidekiq instrumentation emits span events for created_at and enqueued_at, however, this is very spammy for services which bill by the span (span events count as spans). As these events are not really in-line anyhow, it might be nicer to simply store them as attributes _on_ the span instead of as separate events. Currently it's resulting in a total of 5 spans for enqueuing and processing. On the client there is a span for `queue send` with an event of `created_at`. On the server, there is a span for `queue process` and then 2 span events for `created_at` and `enqueued_at` resulting in a total of 5 events.

Could we change these to be attributes instead?

**Comment by akiellor** [comment]
I'm also running into this issue also. Would it be possible to add a configuration option to allow users of the Sidekiq instrumentation to choose how they represent the `created_at` and `updated_at` in their spans?

**Comment by robbkidd** [comment]
Link aggregating!

On [a PR to Sidekiq instrumentation](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/414), there was an attempt to add the times of these job events to the job span along with some math done on the times to compute queue-to-work latency. We have opted not to update the instrumentation to support that at the moment, so I shared [the results of an experiment on that PR](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/414#issuecomment-1692509720) that:

* hoists the timestamps of the `created_at` and `enqueued_at` events up to the span as attributes (as Integers representing the UNIX timestamp, maybe not super valuable)
* performs the calculation: `job.latency_ms = (span.start_time - enqueued_at) / 1_000_000` (pseudo code)

Details and a pretty picture of the results can be found there, but for the purposes of this issue, I'll copy the Collector-contrib config here so folks can see an example of how to use the transform processor as @ericmustin [mentioned](https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/405#issuecomment-1550075125) to copy data from a span-event to its parent span and then drop the span-events.

```yaml
# partial /etc/otelcol-contrib/config.yaml for otelcol-contrib v0.83.0
… 
processors:
  batch:
  transform/joblatency:
    error_mode: ignore
    trace_statements:
      - context: spanevent
        statements:
          - set(span.attributes["job.created_at"], time_unix_nano) where IsMatch(instrumentation_scope.name, "Sidekiq") and name == "created_at"
          - set(span.attributes["job.enqueued_at"], time_unix_nano) where IsMatch(instrumentation_scope.name, "Sidekiq") and name == "enqueued_at"
          - set(span.attributes["job.latency_ms"], ((span.start_time_unix_nano - time_unix_nano) / 1000000)) where IsMatch(instrumentation_scope.name, "Sidekiq") and name == "enqueued_at"
  filter/dropspanevents:
    error_mode: ignore
    traces:
      spanevent:
        - 'IsMatch(instrumentation_scope.name, "Sidekiq") and name == "created_at"'
        - 'IsMatch(instrumentation_scope.name, "Sidekiq") and name == "enqueued_at"'

…

service:
  pipelines:
    traces:
      receivers: […] 
      processors: [transform/joblatency, filter/dropspanevents, batch]
      exporters: […]
```
